services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    stop_signal: SIGINT
    env_file:
      - .env
    volumes:
      - ".env:/app/.env"
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:7.2.5
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
        - "./redis_config/redis.conf:/usr/local/etc/redis/redis.conf"
        - "./redis_data:/data"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    healthcheck:
        test: [ "CMD", "redis-cli","ping" ]